// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf16nsRQ1lmFE6hpgT-47be7dxPbHrpt0',
    appId: '1:474801142290:web:e4af7d06515a9aac47f6cb',
    messagingSenderId: '474801142290',
    projectId: 'ashasahyog-7b006',
    authDomain: 'ashasahyog-7b006.firebaseapp.com',
    storageBucket: 'ashasahyog-7b006.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2e6gfVMHOfbvPG8VWA1NPoeOixHZII0',
    appId: '1:474801142290:android:a49cb47009eca6e647f6cb',
    messagingSenderId: '474801142290',
    projectId: 'ashasahyog-7b006',
    storageBucket: 'ashasahyog-7b006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTe1LVtm6Gkes6eY3SsoQBMgSF3Fad03A',
    appId: '1:474801142290:ios:096f6406a5edfae647f6cb',
    messagingSenderId: '474801142290',
    projectId: 'ashasahyog-7b006',
    storageBucket: 'ashasahyog-7b006.firebasestorage.app',
    iosBundleId: 'com.example.ashaSahyog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTe1LVtm6Gkes6eY3SsoQBMgSF3Fad03A',
    appId: '1:474801142290:ios:096f6406a5edfae647f6cb',
    messagingSenderId: '474801142290',
    projectId: 'ashasahyog-7b006',
    storageBucket: 'ashasahyog-7b006.firebasestorage.app',
    iosBundleId: 'com.example.ashaSahyog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf16nsRQ1lmFE6hpgT-47be7dxPbHrpt0',
    appId: '1:474801142290:web:2c62598e8d4fdb0b47f6cb',
    messagingSenderId: '474801142290',
    projectId: 'ashasahyog-7b006',
    authDomain: 'ashasahyog-7b006.firebaseapp.com',
    storageBucket: 'ashasahyog-7b006.firebasestorage.app',
  );
}
